name: Test VS Code extension (vsce)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vsce-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i 
      - run: npm run compile
      - run: npm run test 
      vsce-on-Ubuntu:
  name: Run npm on Fedora
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i 
      - run: npm run compile
      - run: npm run test 